---
- hosts: localhost
  tasks:
    - name: Create ec2 instance
      ec2_instance:
        key_name: default_ec2
        instance_type: t2.micro
        image_id: ami-0c02fb55956c7d316
        region: us-east-1
        count: 1
        vpc_subnet_id: subnet-082bb22982366b048
        network:
          assign_public_ip: true
        security_group: http_server_sg
        tags:
          Environment: QA
        wait: yes
      register: ec2_output
    - debug: var=ec2_output